// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQA2cDotUID9vGgTgExXpCaDnDLAyoOBM',
    appId: '1:54868201966:web:bafba20390c1c3ec683eff',
    messagingSenderId: '54868201966',
    projectId: 'back2eat-customer',
    authDomain: 'back2eat-customer.firebaseapp.com',
    storageBucket: 'back2eat-customer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYvrOCT0uBKovHquP9nOVRLJE0W9-y2ok',
    appId: '1:450928341853:android:3982807201c0b51dc12eb4',
    messagingSenderId: '450928341853',
    projectId: 'back2eat-prod',
    storageBucket: 'back2eat-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1S2M7qJkvF3ynjgQlI3dMEw1zVex0NTY',
    appId: '1:450928341853:ios:7d81092f34c021cac12eb4',
    messagingSenderId: '450928341853',
    projectId: 'back2eat-prod',
    storageBucket: 'back2eat-prod.firebasestorage.app',
    iosBundleId: 'com.back2eat.app',
  );

}